[profile.default]
src = "contracts/src"
out = "contracts/out"
fs_permissions = [{ access = "read-write", path = "contracts/" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
