[package]
name = "sp1-ics07-tendermint-solidity"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[features]
rpc = ["dep:alloy-contract"]

[dependencies]
alloy-sol-types = { workspace = true, features = ["json"] }
alloy-contract = { workspace = true, optional = true }
tendermint-light-client-verifier = { workspace = true }
serde = { workspace = true }
ibc-client-tendermint-types = { workspace = true }
tendermint = { workspace = true }
ibc-core-commitment-types = { workspace = true }
time = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
