[package]
name = "sp1-ics07-tendermint-utils"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
prost = { workspace = true }
cosmos-sdk-proto = { workspace = true }
tendermint-rpc = { workspace = true }
sp1-ics07-tendermint-solidity = { workspace = true }
tendermint-light-client-verifier = { workspace = true }
ibc-client-tendermint-types = { workspace = true }
ibc-core-client-types = { workspace = true }
ibc-core-host-types = { workspace = true }
tendermint = { workspace = true }
ibc-core-commitment-types = { workspace = true }
alloy = { workspace = true }

union-protos = { workspace = true }
unionlabs = { workspace = true }
