name: e2e
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - '**.rs'
      - '**.go'
      - '**.toml'
      - '**.lock'
      - '**.mod'
      - '**.sum'
      - '**.sol'
      - '.github/workflows/e2e.yml'
env:
  FOUNDRY_PROFILE: ci
permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0
        with:
          version: v1.60
          args: --timeout 5m
          working-directory: e2e/interchaintestv8
  e2e:
    strategy:
      fail-fast: false
      matrix:
        test:
          # List your tests here
          - TestWithSP1ICS07TendermintTestSuite/TestDeploy_Groth16
          - TestWithSP1ICS07TendermintTestSuite/TestDeploy_Plonk
          - TestWithSP1ICS07TendermintTestSuite/TestUpdateClient_Groth16
          - TestWithSP1ICS07TendermintTestSuite/TestUpdateClient_Plonk
          - TestWithSP1ICS07TendermintTestSuite/TestMembership_Union
          - TestWithSP1ICS07TendermintTestSuite/TestMembership_Groth16
          - TestWithSP1ICS07TendermintTestSuite/TestMembership_Plonk
          - TestWithSP1ICS07TendermintTestSuite/TestUpdateClientAndMembership_Groth16
          - TestWithSP1ICS07TendermintTestSuite/TestUpdateClientAndMembership_Plonk
          - TestWithSP1ICS07TendermintTestSuite/TestDoubleSignMisbehaviour_Groth16
          - TestWithSP1ICS07TendermintTestSuite/TestDoubleSignMisbehaviour_Plonk
          - TestWithSP1ICS07TendermintTestSuite/TestBreakingTimeMonotonicityMisbehaviour_Groth16
          - TestWithSP1ICS07TendermintTestSuite/TestBreakingTimeMonotonicityMisbehaviour_Plonk
    name: ${{ matrix.test }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          check-latest: true
          cache-dependency-path: e2e/interchaintestv8/go.sum
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Get SP1 version
        id: sp1-version
        run: |
          sp1_version=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "sp1-sdk") | .version')
          echo "sp1_version=v$sp1_version" >> $GITHUB_OUTPUT
      - name: Install SP1 toolchain
        run: |
          curl -L https://raw.githubusercontent.com/succinctlabs/sp1/${{ steps.sp1-version.outputs.sp1_version }}/sp1up/install | bash
          ~/.sp1/bin/sp1up --token ${{ secrets.GITHUB_TOKEN }}
          ~/.sp1/bin/cargo-prove prove --version
      - name: Install just
        uses: extractions/setup-just@v2
      - name: Build operator
        run: just build-operator
      - name: "Install Bun"
        uses: "oven-sh/setup-bun@v1"
      - name: "Install the Node.js dependencies"
        run: bun install
      - name: Run Tests
        env:
          SP1_PRIVATE_KEY: ${{ secrets.SP1_PRIVATE_KEY }}
        run: |
          cd e2e/interchaintestv8
          go test -v -mod=readonly . -run '^${{ matrix.test }}$' -timeout 40m
