name: programs

on: 
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-programs:
    strategy:
      fail-fast: false
      matrix:
        programs:
          # List your program directories here
          - programs/update-client
          - programs/membership
          - programs/uc-and-membership
          - programs/misbehaviour
    name: 'build: ${{ matrix.programs }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up --token ${{ secrets.GITHUB_TOKEN }}
          ~/.sp1/bin/cargo-prove prove --version

      - name: Build SP1 program
        run: |
          cd ${{ matrix.programs }}
          ~/.sp1/bin/cargo-prove prove build
