name: upload-programs

on: 
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  upload:
    strategy:
      fail-fast: true
    name: build-and-upload
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up 
          ~/.sp1/bin/cargo-prove prove --version
      - name: Install just
        uses: extractions/setup-just@v2

      - name: Build SP1 Programs
        run: just build-programs
      - name: Upload Programs
        uses: actions/upload-artifact@v4
        with:
          name: program-elfs
          path: elf/
          retention-days: 5
